version: '3'

env:
  VM_COUNT: 2
  SHARED_IMAGE_GALLERY_NAME: '{{REPLACE_ME}}'
  SHARED_IMAGE_NAME: '{{REPLACE_ME}}'

tasks:
  up:
    desc: Creates a complete Azure environment 
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    - terraform apply -auto-approve -var "region={{.REGION}}" -compact-warnings
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  runners:
    desc: Creates a Automation Hybrid Runers
    cmds:
    - terraform -chdir=./runners workspace new {{.NEW_WORKSPACE_NAME}} || true
    - terraform -chdir=./runners workspace select {{.NEW_WORKSPACE_NAME}}
    - terraform -chdir=./runners init
    - terraform -chdir=./runners apply -auto-approve -var "app_name={{.APP_NAME}}" -var "number_of_runners={{.VM_COUNT}}" -var "automation_account_url={{.AUTOMATION_ACCOUNT_URL}}" -compact-warnings
    - terraform -chdir=./runners workspace select {{.OLD_WORKSPACE_NAME}} 
    - terraform -chdir=./runners destroy -auto-approve -var "app_name={{.APP_NAME}}" -var "number_of_runners={{.VM_COUNT}}" -var "automation_account_url={{.AUTOMATION_ACCOUNT_URL}}" -compact-warnings 
    vars: 
      APP_NAME: '{{default .CLI_ARGS}}'
      AUTOMATION_ACCOUNT_URL: 
        sh: terraform output -raw AUTOMATION_ACCOUNT_URL
      NEW_WORKSPACE_NAME:
        sh: echo {{.APP_NAME}}-`date +"%Y%m%d"`
      OLD_WORKSPACE_NAME: 
        sh: echo {{.APP_NAME}}-`date +"%Y%m%d" -d "last week"`

  packer:
    desc: Creates a Gold Image in Azure's Shared Image Gallery
    dir: ./packer
    cmds:
    - packer init ./azure_linux.pkr.hcl
    - packer build -var "build_version={{.BUILD_VERSION}}" -var "shared_image_gallery_name={{.SHARED_IMAGE_GALLERY_NAME}}" -var "shared_image_name={{.SHARED_IMAGE_NAME}}".
    vars: 
      APP_NAME: '{{default .CLI_ARGS}}'
      BUILD_VERSION:
        sh: date +"%U"

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - cd ./runners; rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group list --tag Application="Hybrid Worker Automation Runners" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose -n
    - az group list --tag Application="Hybrid Worker Automation Demo" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose -n
