version: '3'

env:
  TITLE: "Multi-region Azure Redis Enterprise Cache demo"

tasks:
  up:
    desc: Creates {{.TITLE}} Azure infrastructure
    cmds:
    - terraform init
    - terraform apply -auto-approve -var "tags={{.TITLE}}"

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TITLE}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --no-wait -n || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true