version: '3'

env:
  APP_NAME: werewolf-31947
  RG: '{{.APP_NAME}}_rg'

tasks:
  up:
    desc: Builds end to end an ASEv3 Internal environment
    cmds:
    - task: init
    - task: apply

  init: 
    desc: Initializes Azure Resource Group
    cmds:
    - az group create -n {{.RG}} -l {{.REGION}}
    vars:
      REGION: '{{default "canadaeast" .CLI_ARGS}}'

  apply: 
    desc: Applies Terraform configuration
    cmds:
    - az group deployment create -g {{.RG}} --template-file ./logicapp.json --parameters ./logicapp.parameters.json --verbose 
    
  down:
    desc: Destroys all Azure resources 
    cmds:
    - az group delete -n {{.RG}} --yes --no-wait --verbose || true
