version: '3'

vars:
  DEFAULT_REGION: 'northcentralus'
  TAG: "Azure Virtual Machine"
  VM_TYPE: Linux

tasks:
  default:
    cmds:
    - task --list 

  up:
    desc: Builds an {{.VM_TYPE}} {{.TAG}}
    cmds:
    - task: init
    - task: apply

  init: 
    desc: Initializes Terraform
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply: 
    desc: Applies Terraform configuration
    cmds:
    - terraform apply -auto-approve -var "region={{.REGION}}" -var "tags={{.TAG}}" -var "vm_type={{.VM_TYPE}}"
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  password:
    desc: Outputs the password for the VM
    cmds:
    - terraform output -raw WINDOWS_ADMIN_PASSWORD

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TAG}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --no-wait -n || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true